[context.production.environment]
  HUGO_VERSION = "0.139.0"
  # HUGO_GOOGLE_ANALYTICS_ID = "GA-XX"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.139.0"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.139.0"
